

# GET https://final-project-dw2.onrender.com/usuarios
GET https://final-project-dw2.onrender.com/encomendas
###cria

###

###recupera
# POST https://final-project-dw2.onrender.com/usuarios
POST https://final-project-dw2.onrender.com/encomendas
Content-type: application/json

{
    "cliente":"teste",
    "estilista": "teste",
    "tipoEncomenda": "teste",
    "valor": 100
}


### 

### deleta
DELETE https://final-project-dw2.onrender.com/encomendas/{id}
# DELETE https://final-project-dw2.onrender.com/usuarios/980bb7d3-ddc1-45e9-a35f-187841de5501


###

### atualiza
PUT https://final-project-dw2.onrender.com/encomendas/c8dedf6d-6cdd-4f93-94c1-551f22dc8b46
Content-type: application/json

{
    "cliente": "giovana 2",
    "estilista": "John Galliano",
    "tipoEncomenda": "calça pantalona de oncinha",
    "valor": "10000.00"
}