

# GET https://final-project-dw2.onrender.com/usuarios
GET https://final-project-dw2.onrender.com/encomendas
###cria

###

###recupera
# POST https://final-project-dw2.onrender.com/usuarios
POST https://final-project-dw2.onrender.com/encomendas
Content-type: application/json

# {
#     "cliente": "Maria",
#     "estilista": "alexander mcqueen",
#     "tipoEncomenda": "vestido",
#     "horarioPedido": "2004-10-19 10:23:54",
#     "valor": 120.00
# }

### 

### deleta
DELETE https://final-project-dw2.onrender.com/encomendas/980bb7d3-ddc1-45e9-a35f-187841de5501
# DELETE https://final-project-dw2.onrender.com/usuarios/980bb7d3-ddc1-45e9-a35f-187841de5501


###

### atualiza
PUT https://final-project-dw2.onrender.com/encomendas/20a9a3f5-36a8-47b1-b8c0-7019520c84ec
# PUT https://final-project-dw2.onrender.com/usuarios/20a9a3f5-36a8-47b1-b8c0-7019520c84ec
Content-type: application/json

# {
#     "cliente": "Maria 2",
#     "estilista": "maria2@gmail.com",
#     "tipoEncomenda": "555",
#     "horarioPedido": "220723",
#     "valor": "200,00"
# }